version: "3.8"

services:

    redis:
        image: redis
        command: redis-server
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
        ports:
            - "9201:9200"
            - "9301:9300"
        environment:
            - xpack.security.enabled=false
            - network.host=127.0.0.1
            - http.host=0.0.0.0
    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.13
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - elasticsearch
    pgsync:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "chmod +x ./docker/runserver.sh && ./docker/runserver.sh"
        tty: true

        volumes:
            - .:/code
        sysctls:
            - net.ipv4.tcp_keepalive_time=200
            - net.ipv4.tcp_keepalive_intvl=200
            - net.ipv4.tcp_keepalive_probes=5
        labels:
            org.label-schema.name: "pgsync"
            org.label-schema.description: "Postgres to Elasticsearch sync"
            com.label-schema.service-type: "daemon"
        depends_on:
            - redis
            - elasticsearch
        environment:
            - PG_USER=postgres
            - PG_HOST=192.168.2.43
            - PG_PORT=5432
            - PG_PASSWORD=Upbase2022
            - LOG_LEVEL=DEBUG
            - ELASTICSEARCH_PORT=9200
            - ELASTICSEARCH_SCHEME=http
            - ELASTICSEARCH_HOST=elasticsearch
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_AUTH=
            - ELASTICSEARCH_TIMEOUT=300
            - ELASTICSEARCH=true
            - QUERY_CHUNK_SIZE=100
            - ELASTICSEARCH_CHUNK_SIZE=100
            - CONSOLE_LOGGING_HANDLER_MIN_LEVEL=DEBUG
            - CHECKPOINT_PATH=/code/checkpoint_path
volumes:
    pgsync_staging_new: {}

